### PR TITLE
Missing qt package under Linux

### PR DESCRIPTION
**Pull request by drouin-simon**
The current version of OpenIGTLinkIO doesn't build under Linux when GUI support in enabled. More specifically, CMake fails to generate the makefile because the target Qt5::X11Extras is not found.

Qt5::X11Extras is a dependency of VTK when VTK is built with Qt GUI support. For some reason, VTK lists the package as a private dependency (see the code in vtk repos [here](https://github.com/Kitware/VTK/blob/4c4f2effedf9a7caaccee57bf92c6a4a7291ae70/GUISupport/Qt/CMakeLists.txt#L83) ), which means you need to make sure the target Qt5::X11Extras is explicitly defined in any projects that uses this module of VTK. 

What I don't understand is that the Qt5::X11Extras target needs to be defined in the base directory of OpenIGTLinkIO (and not just the GUI directory) otherwise cmake produces an error when generating the makefile. This pull request makes sure the target is defined in the root directory and I added a comment to make it obvious it is a workaround. The cleaner solution I think would be for VTK to define the package as a public dependency.

### CODE REVIEW

**Comment by drouin-simon** [comment]
Any thoughts about this PR. Should I just merge it?

**Comment by adamrankin** [comment]
Hmm, what is the error when Qt5::X11Extras is only defined in the GUI directory?

**Comment by adamrankin** [comment]
And what version of VTK is this with?

**Comment by adamrankin** [comment]
It looks like X11Extras is only enabled once Module_vtkGUISupportQtOpenGL is enabled.

**Comment by adamrankin** [comment]
I do not get a configure error looking for x11extras. 

Using: Ubuntu 16.04, qt5.5.1, vtk 9.0.0

Testing now with Slicer's vtk

**Comment by adamrankin** [comment]
After enabling IGTLIO_GUI in Slicer extension nightly build:

No configure error with Ubuntu 16.04, Slicer nightly's VTK, qt5.9.

Build error though!

**Comment by adamrankin** [comment]
Can you post your configure log with the error and your CMakeCache.txt?

**Comment by drouin-simon** [comment]
This is the output of CMake when I generate makefile:

CMake Error at GUI/CMakeLists.txt:161 (add_library):
  Target "igtlioGUI" links to target "Qt5::X11Extras" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at Examples/qIgtlClient/CMakeLists.txt:31 (add_executable):
  Target "igtlioQtClient" links to target "Qt5::X11Extras" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at GUI/CMakeLists.txt:161 (add_library):
  Target "igtlioGUI" links to target "Qt5::X11Extras" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at Examples/qIgtlClient/CMakeLists.txt:31 (add_executable):
  Target "igtlioQtClient" links to target "Qt5::X11Extras" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

Generating done

**Comment by drouin-simon** [comment]
I have the problem on both Ubuntu 16.04 and 18.04 with vtk-7.1.1 and old OpenGL backend. I have vtkGUISupportQt enabled, but not vtkGUISupportQtOpenGL.

**Comment by drouin-simon** [comment]
Also, I use Qt 5.9.5 on 18.04 and 5.5.1 on 16.04

**Comment by drouin-simon** [comment]
Here are the cache and the log:

[CMakeCache.txt](https://github.com/IGSIO/OpenIGTLinkIO/files/2278874/CMakeCache.txt)
[CMakeOutput.log](https://github.com/IGSIO/OpenIGTLinkIO/files/2278879/CMakeOutput.log)

**Comment by drouin-simon** [comment]
The problem seems to come from vtk. In vtkQt, you have those lines in the CMakeLists.txt

```
set(QT_LIBRARIES_PRIVATE ${Qt5X11Extras_LIBRARIES})
...
vtk_module_link_libraries(${vtk-module} LINK_PRIVATE ${QT_LIBRARIES_PRIVATE})
```
So the library is linking with Qt5X11Extras, but it is not telling its clients to do so.

**Comment by adamrankin** [comment]
Ok, probably an old VTK issue. Perhaps add a comment that this is a workaround for VTK 7.1.1? After that, looks good to me.

**Pull request merged**
