### PR TITLE
STYLE: Remove igtlio namespace

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
re #47

### CODE REVIEW

**Comment by adamrankin** [comment]
It looks good to me, but just in case, how did you perform this change?

Search for all "namespace igtlio" using a find in files search tool (notepad++)?

**Comment by leochan2009** [comment]
Looks good to me too.
Do you guys think it is a good idea to add the super build,  travis CI and AppVeyor automatic test to the OpenIGTLinkIO?  So we could check if all functionality work during development.
I had started the implementation of SuperBuild for the purpose of automatic test some time ago and would like to continue if you think it is necessary.

**Comment by Sunderlandkyl** [comment]
Found and removed all instances of "namespace igtlio" using total commander.
Renamed classes from igtlio::XYZ to igtlioXYZ where it occurred.

There is one change that I'm still not sure about.

There are a couple of free functions that used to exist in the igtlio namespace, but now exist in the global namespace.
I moved one of them into it's related class (CreateDeviceKey() --> igtlioDeviceKeyType::CreateDeviceKey()).

There a bunch of others in igtlioTestUtilities.cxx that I'm not sure what to do with.
(https://github.com/Sunderlandkyl/OpenIGTLinkIO/blob/1f60142680142dc7dcc8d7b85984d2ed598a67e7/Testing/igtlioTestUtilities.cxx)

Perhaps it would be OK to leave them as free functions if they had more descriptive names?
Either that or convert igtlioTestUtilities to a class with static methods?

**Comment by adamrankin** [comment]
If they only exist in the .cxx file put them in an anonymous namespace.

**Comment by olevs** [comment]
You may add igtlio in front of the functions in global namespace to avoid problems. More descriptive names is usually a good idea (like compareMatrices and compareImages), but still I think you need to add igtlio or put them in a class to avoid conflicts.

**Comment by adamrankin** [comment]
Ah, I misunderstood. @olevs solution is correct, prefix with igtlio for the function names or put them in a class as static functions.

**Pull request merged**
