### PR TITLE
EHN: Added new converter type for video data, in progress

### PR DESCRIPTION
**Pull request by leochan2009**
Just created a converter for video stream, will work on the igtliodevice soon.

### CODE REVIEW

**Comment by adamrankin** [comment]
Thanks so much for effort on video streaming. Since Junichi is going to be joining us at our satellite project week, would you be willing to bring him up to speed on how to configure this setup (if he's not already comfortable)? I'd love to set this up for our streaming ultrasound.

**Comment by leochan2009** [comment]
Hi Adam,

Sure, i will update Junichi on the the VideoStreaming stuff. 
I also made some modification on the plusBuild to integrate the video Streaming, though still in my forked branch.
I will try to merge it back to PlusBuild soon.
Hope it will be helpful If you are testing ultrasound streaming  using Plus library.

**Comment by adamrankin** [comment]
That's awesome, I will see if I can make time to check this out during our project week.

(pasting link for my convenience)
https://github.com/leochan2009/PlusLib

**Comment by adamrankin** [comment]
Would you be able to investigate the OpenIGTLinkIO build? It is currently failing while looking for igtlVideoMessage.h

**Comment by leochan2009** [comment]
Hi Adam,
did you link to the correct version of OpenIgtlink?
The cmake variable OpenIGTLink_DIR should set to build directory this branch:
 https://github.com/openigtlink/OpenIGTLink/tree/VideoStreamMerge
Let me know if you have further question.

Best Regards,
Longquan

**Comment by adamrankin** [comment]
Hmm, we do not want to point to a branch of OpenIGTLink. Could you merge that work into master or revert the changes to OpenIGTLinkIO?

**Comment by leochan2009** [comment]
I see, i need to discuss with Junichi about the merge. 
As this work is still primitive...

**Comment by leochan2009** [comment]
I will remove the OpenIGTLinkIO link to video message for now

**Comment by leochan2009** [comment]
Hi Adam,

I just tagged the previous openigtlink master branch as release-3.0.0, and create a pull request to merge the video streaming branch into the master.
Let's wait for Junichi's response.
Best Regards,
Longquan

**Comment by leochan2009** [comment]
@adamrankin ,

I just merge the video streaming branch into the master branch.
Are you meeting with Junichi in the project week? 
Any feedbacks are welcomed.

Best Regards,
Longquan

**Pull request merged**
