### PR TITLE
Add additional mutex locks around Connector.Sockets iterators

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
Sorry @adamrankin for making so many pull requests.
Hopefully this should fix the last issue.

Apparently ```for(auto& client : Sockets)``` is thread safe (didn't know that), while ```for(std::vector<T>::iterator...)``` is not.

Is the appropriate solution to lock each connector.Sockets reference with a mutex, or to restrict access to a specific thread?

### CODE REVIEW

**Comment by adamrankin** [comment]
It's fine to lock each connector.Sockets reference

**Review by adamrankin — APPROVED** [review]

**Comment by Sunderlandkyl** [comment]
I had to test some things to be sure, but the way that it's set up currently can cause some issues.

Ex.
- Calling GetClient (through SendCommand, or however) on a connector that is not actively receiving data:
  - ThreadFunction: ReceiveController locks to iterate over the sockets, and waits for incoming data
```(clientIt->Socket->Receive(headerMsg->GetPackPointer(), headerMsg->GetPackSize()))```
  - MainThread: GetClient tries to lock. Forced to wait until all sockets in ThreadFunction receive data (which could be never)

**Comment by adamrankin** [comment]
Ah, can Receive timeout and we can just go through the loop again?

**Comment by adamrankin** [comment]
In fact, it has too so that multiple clients can be processed.

**Comment by Sunderlandkyl** [comment]
Yes, this was my though as well. It currently does not, and it'll wait at each socket without moving on unless data is received.

Is there a timeout option for int Socket::Receive()?

**Comment by Sunderlandkyl** [comment]
Nevermind I found it.

**Comment by Sunderlandkyl** [comment]
I'm not sure what an appropriate timeout would be. Currently I've setup a 1ms timeout.

It seems to have solved the locking issue.

**Comment by adamrankin** [comment]
Yes, very short. 1-5ms is fine.

**Comment by Sunderlandkyl** [comment]
Great, thanks @adamrankin!

**Pull request merged**
